### ISSUE TITLE
OrchardCore.ProjectTemplates::1.0.0-* is not supported.

### ISSUE THREAD

**Issue by atorres16** [Lombiq/Utility-Scripts#13]
I tried to follow the instructions on https://www.youtube.com/watch?v=cQJeS21wZHw&list=PLuskKJW0FhJcSX7j0Bd-1X5hq3dgCtYwO&index=2

But got the following error

```
Local\DojoCourse> Init-OrchardCoreSolution -Name "DojoCourse" -ModuleName "DojoCourse.Module" -ThemeName "DojoCourse.Theme"
The following template packages will be installed:
   OrchardCore.ProjectTemplates::1.0.0-*

OrchardCore.ProjectTemplates::1.0.0-* is not supported.
No templates found matching: 'occms'.

To list installed templates, run:
   dotnet new --list
To search for the templates on NuGet.org, run:
   dotnet new occms --search
```

**Comment by atorres16** [comment]
Following the instructions on the error message I ran:
```
dotnet new --install OrchardCore.ProjectTemplates
dotnet new --install OrchardCore.Cms.Templates
```
Then I tried again, a project was created, but the error still showed

![image](https://user-images.githubusercontent.com/19210281/143639883-943a21af-f38e-4314-af20-c0945dd80751.png)

**Comment by atorres16** [comment]
I did noticed there's a newest version of this projecttemplates thing

https://www.nuget.org/packages/OrchardCore.ProjectTemplates/

It's already installed though 

```OrchardCore.ProjectTemplates::1.1.0 is already installed.```

**Comment by atorres16** [comment]
Project won't build

![image](https://user-images.githubusercontent.com/19210281/143655851-59485f15-3330-4215-a59c-a6fc3a709d9c.png)

**Comment by Piedone** [comment]
Thanks for letting us know. This is quite strange, as our script references the OC version directly. So even if there's an 1.1 out there and we haven't yet modified the script, it should work. And it does for me, this creates a solution properly though it does tell about the available update:

```
Init-OrchardCoreSolution -Name "FancyWebsite" -ModuleName "FancyWebsite.Core" -ThemeName "FancyWebsite.Theme"
```
The resulting solution builds properly as well.

I'm really at a loss of what the issue might be on your machine, especially that the VS build errors of yours seem to reference the beta packages. Are you sure you're using the latest scripts?

**Comment by Piedone** [comment]
Closing due to lack of reply.
