### ISSUE TITLE
Installing the PowerShell modules small issue

### ISSUE THREAD

**Issue by kudryavtsevda** [Lombiq/Utility-Scripts#14]
I was stuck with PS script AddPathToPSModulePath.ps1. I was trying to follow this [instructions](https://github.com/Lombiq/Utility-Scripts/blob/dev/Readme.md#installing-the-powershell-modules). After running this command the script 'Init-OrchardCoreSolution' was not recognized still. So I had to restart my PS console and after second attempt it worked out.
Could you update your instruction with small hint that PS command console should be restarted after successful run of AddPathToPSModulePath.ps1 script?

**Comment by Piedone** [comment]
Good point, yes, you indeed need to restart the console.

Would you like to venture into opening a PR for this? (You can just do this from GitHub online by editing the file, no need to clone it.) That way, you'll also show up among the contributors :).
