### ISSUE TITLE
dotnet new -i is obsolete (OSOE-459)

### ISSUE THREAD

**Issue by agriffard** [Lombiq/Utility-Scripts#23]
Warning using `Initialize-OrchardCoreSolution`:

`'dotnet new -i' is obsolete. Use 'dotnet new install' instead.`

https://github.com/Lombiq/Utility-Scripts/blob/7e83e0f71448af66e05d89162772acd3c32ac5f7/OrchardCore/Initialize-OrchardCoreSolution/Initialize-OrchardCoreSolution.psm1#L33

I guess it will be soon updated to OC version 1.5.0

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-459)

**Comment by Piedone** [comment]
Thank you, will look into this.
