### ISSUE TITLE
Init-OrchardCoreSolution initialize error 

### ISSUE THREAD

**Issue by maksudcs** [Lombiq/Utility-Scripts#4]
> Init-OrchardCoreSolution -Name "Jobprep" -ModuleName "Jobprep.Core" -ThemeName "Jobprep.Theme"

Init-OrchardCoreSolution : The term 'Init-OrchardCoreSolution' is not
recognized as the name of a cmdlet, function, script file, or operable
program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:1 char:1
+ Init-OrchardCoreSolution -Name "Jobprep" -ModuleName "Jobprep.Core" - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Init-OrchardCoreSolution:String
   ) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Piedone** [comment]
Have you done the installation? https://github.com/Lombiq/Utility-Scripts#installing-the-powershell-modules

**Comment by ossan-dev** [comment]
Hi @maksudcs 
sorry if I'm a bit later in the party but I discovered Orchard recently.
Anyway I was able to run the script in the following way:  

1. Create an empty folder, let's say "DojoCourse"
2. After that download the files "AddPathToPSModulePath.ps1" and "Init-OrchardCoreSolution.psm1"
3. Copy these two files in the newly created folder
4. Open the folder with Powershell in admin mode
5. Run "Set-ExecutionPolicy Unrestricted"
6. Run the "AddPathToPSModulePath.ps1" with Powershell
7. Now check the environment variable of your machine: u should see a system variable named "PSModulePath" with the path of your "DojoCourse" directory
8. Now u'll be able to run => Init-OrchardCoreSolution -Name "DojoCourse" -ModuleName "DojoCourse.Core" -ThemeName "DojoCourse.Theme"

**Note** that I still get an issue on a git file but now at least it should work.

This workaround is based on:

- Windows 10
- Powershell version: 5.1 build 19041 revision 1023

Let me know if it helps.

**Comment by Piedone** [comment]
Yes, these are our installation instructions :) https://github.com/Lombiq/Utility-Scripts#installing-the-powershell-modules

**Comment by ossan-dev** [comment]
@Piedone u're right of course 😂
I'm only detailed a little bit in the hope that it could help.

**Comment by Piedone** [comment]
Thank you for that! :)

I'm closing this issue now because @maksudcs didn't reply.

**Comment by sushant-choudhary** [comment]
> 7\. see a system variable named "PSModulePath" with the path of your "DojoCourse" directory

I followed it until step 6 but did not see a system variable named "PSModulePath" with the path of your "DojoCourse" directory in my PATH variable

**Comment by Piedone** [comment]
See the current installation instructions, please: https://github.com/Lombiq/Utility-Scripts#installing-the-powershell-modules And the prerequisites: https://github.com/Lombiq/Utility-Scripts#prerequisites
